export default {
  SET_DEPENDENCE: "config/SET_DEPENDENCE",
  SET_PRODUCT_NAME: "config/SET_PRODUCT_NAME",
  SET_PRODUCT_OWNER: "config/SET_PRODUCT_OWNER",
  SET_DOMAIN: "config/SET_DOMAIN",
  UPLOAD_TASKS: "session/UPLOAD_TASKS",
  PERFORMED_TASK: "session/PERFORMED_TASK",
};
